### ISSUE TITLE
KakaoTalk Replica QA Feedback

### ISSUE THREAD

**Issue by harrythemonster** [MoonWanki/kakaotalk-replica#1]
KakaoTalk Replica QA에 참여하였습니다.
여러 테스트를 통해 아래 버그들을 확인하였습니다. 

1. 회원 가입시 프로필 사진 지정안하면 에러

2. 채팅창에서 텍스트 내용이 길어지면 프로필 사진이 상대적으로 작아짐 (메세지 송수신자 모두에게서 발생)

3. 특수문자 길게 입력할 경우 줄바꿈 기능 구현 안됨

![image](https://user-images.githubusercontent.com/29115589/54487210-a6ca7c80-48d6-11e9-991e-2cdc157c5fce.png)

(글자와 특수문자를 같이 쓸 경우에도 발생)
![image](https://user-images.githubusercontent.com/29115589/54487174-17bd6480-48d6-11e9-86c3-4ec00daa8da0.png)

4. 이미지와 사용자 명과의 간격이 좁음 (UI적 요소)

![image](https://user-images.githubusercontent.com/29115589/54487186-4cc9b700-48d6-11e9-850c-abde15ad76dc.png)

추후 새로운 사항 발견시 업로드 하겠습니다.

**Comment by aibees** [comment]
버그 관련 comment.
1. 자동 로그인 체크 후 로그인은 잘 됨. 그러나 다른 탭에서 접속하면 자동으로 되긴 하지만
처음 로그인 한 창에서는 강제 로그아웃 됨. 그러고 나서 로그아웃하면 오류 발생

2. 계정 생성 시 닉네임과 썸네일 입력 없이 enter로 접속하면 정상적인 계정생성 불가
